include:
  - project: cms-cactus/phase2/firmware/ci-templates
    ref: e989e8d3b0ce7091bba09291639fc0565f4555ba
    file: vivado/all.yml
  - /pf/gitlab-ci.yml
  - /puppi/gitlab-ci.yml
  - /l1-regionizer/multififo/gitlab-ci.yml
  - /egamma/l1-input/gitlab-ci.yml
  - /egamma/l1-tkeg/gitlab-ci.yml
  - /egamma/l1-isolation/gitlab-ci.yml


default:
  tags: [vivado20192]

variables:
  VIVADO_VERSION: '2019.2'


workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^test/
    - if: $CI_PIPELINE_SOURCE == "web"


    

stages:
  - sim
  - pre-build
  - build
  - test
  - deploy
