.l1reg-multififo-common:
  variables:
    pfBoard: none
    pfReg: HGCal
    WORKDIR: l1-regionizer/multififo
  rules:
    - if: '( $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^test/ )'
      changes: 
        - l1-regionizer/common/**/*
        - l1-regionizer/multififo/**/*
        - egamma/l1-input/**/*
        - dataformats/**/*
        - data/**/*
        - utils/**/*
        - common/**/*
    - if: '( $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "web" )'


l1reg-multififo:csim:
  extends: [ .vivado_hls_csim, .l1reg-multififo-common ]
  tags: [ vivado20192-csim ]
  variables:
    VIVADO_HLS_LOG_ID: l1r-mf-$${regionizerMode}
    VIVADO_HLS_TCL_SCRIPT: run_hls_csim.tcl
  parallel:
    matrix:
      - regionizerMode: [nomux, mux, stream]


l1reg-multififo-unpackers:csim:
  extends: [ .vivado_hls_csim, .l1reg-multififo-common ]
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: VCU118
    VIVADO_HLS_LOG_ID: l1reg-multififo-unpackers
    VIVADO_HLS_TCL_SCRIPT: run_hls_unpackers.tcl

l1reg-multififo-tdemux:csim:
  extends: [ .vivado_hls_csim, .l1reg-multififo-common ]
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: VCU118
    VIVADO_HLS_LOG_ID: l1reg-multififo-tdemux
    VIVADO_HLS_TCL_SCRIPT: run_hls.tcl
    WORKDIR: l1-regionizer/multififo/tdemux
 
.l1reg-multififo-vhdl-common:
  extends: [ .vivado_base, .l1reg-multififo-common ]
  stage: pre-build
  variables:
    WORKDIR: l1-regionizer/multififo/vhdl/firmware/testbench

l1reg-multififo-simple:sim:
  extends: .l1reg-multififo-vhdl-common
  dependencies:
    - 'l1reg-multififo:csim: [nomux]'
    - 'l1reg-multififo:csim: [mux]'
    - 'l1reg-multififo:csim: [stream]'
  script:
    - ./run_vhdltb.sh vhdl-nomux-tk check
    - ./run_vhdltb.sh vhdl-nomux-calo check
    - ./run_vhdltb.sh vhdl-nomux-mu check
    - ./run_vhdltb.sh vhdl-mux-tk check
    - ./run_vhdltb.sh vhdl-stream-tk  check

l1reg-multififo-full:sim:
  extends: .l1reg-multififo-vhdl-common
  stage: build
  dependencies:
    - 'l1reg-multififo:csim: [nomux]'
    - 'l1reg-multififo:csim: [mux]'
    - 'l1reg-multififo:csim: [stream]'
    - 'eg-l1-input-hgcal:csynth'
  script:
    - ./run_vhdltb.sh vhdl-nomux-all check
    - ./run_vhdltb.sh vhdl-mux-all check
    - ./run_vhdltb.sh vhdl-stream-all check
