.pf-hls-common:
  variables:
    VIVADO_HLS_LOG_ID: $${PF_ALGO_TAG}
    VIVADO_HLS_TCL_SCRIPT: run_hls_$${PF_ALGO_TAG}.tcl
    WORKDIR: pf
  parallel:
    matrix:
      - PF_ALGO_TAG: pfalgo3
        pfReg: Barrel
      - PF_ALGO_TAG: pfalgo2hgc
        pfReg: HGCal

pf:csim:
  extends:
    - .vivado_hls_csim
    - .pf-hls-common
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: none
  rules:
    - if: '( $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^test/ )'
      changes: 
        - pf/**/*
        - dataformats/**/*
        - data/**/*
        - utils/**/*
        - common/**/*
    - if: '( $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "web" )'



pf:csynth:
  extends:
    - .vivado_hls_csynth
    - .pf-hls-common
  tags: [ vivado20192-big ]
  variables:
    pfBoard: VCU118
