.eg-l1-tkeg-iso-hls-common:
  variables:
    VIVADO_HLS_LOG_ID: egamma_$${pfReg}
    VIVADO_HLS_TCL_SCRIPT: run_hls_pftkegisolation.tcl
    WORKDIR: egamma/l1-isolation
  parallel:
    matrix:
      - pfReg: Barrel
      - pfReg: HGCal

eg-l1-tkegiso:csim:
  extends:
    - .vivado_hls_csim
    - .eg-l1-tkeg-iso-hls-common
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: none
  rules:
    - if: '( $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^test/ )'
      changes: 
        - egamma/l1-tkeg/ref/*
        - egamma/l1-isolation/**/*
        - dataformats/**/*
        - data/**/*
        - utils/**/*
        - common/**/*
    - if: '( $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "web" )'



eg-l1-tkegiso:csynth:
  extends:
    - .vivado_hls_csynth
    - .eg-l1-tkeg-iso-hls-common
  tags: [ vivado20192 ]
  variables:
    pfBoard: VCU118
