.eg-l1-input-hgcal-hls-common:
  variables:
    VIVADO_HLS_LOG_ID: eginput_hgcal
    VIVADO_HLS_TCL_SCRIPT: run_hls_eginput_hgcal.tcl
    WORKDIR: egamma/l1-input
    pfReg: HGCal

eg-l1-input-hgcal:csim:
  extends:
    - .vivado_hls_csim
    - .eg-l1-input-hgcal-hls-common
  tags: [ vivado20192-csim ]
  variables:
    pfBoard: none
  rules:
    - if: '( $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^test/ )'
      changes: 
        - egamma/l1-input/**/*
        - dataformats/**/*
        - data/**/*
        - utils/**/*
        - common/**/*
    - if: '( $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "web" )'



eg-l1-input-hgcal:csynth:
  extends:
    - .vivado_hls_csynth
    - .eg-l1-input-hgcal-hls-common
  tags: [ vivado20192 ]
  variables:
    pfBoard: VCU118
  stage: pre-build # run earlier
  rules: # intentionally override the default synth rules to run this by default
    - if: '( $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^test/ )'
    - if: '( $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "web" )'


